### PR TITLE
Bump Rasa OSS to 3.0.0rc1

### PR DESCRIPTION
**Pull request by rasabot**

### CODE REVIEW

**Comment by HotThoughts** [comment]
FYI, this is created *before* this https://github.com/RasaHQ/rasa-x-demo/pull/57. 🥲

**Comment by erohmensing** [comment]
@HotThoughts so I guess we should close this? Or just not merge it?

**Comment by HotThoughts** [comment]
Not sure. If we will need 3.0.0rc1 somehow, we could leave it? Otherwise, there is no reason to keep it open.

**Comment by HotThoughts** [comment]
Rasa 3.0.0 is out.

**Pull request closed without merging**
