### PR TITLE
train a new model with Rasa 1.6.0a2 for the Rasa X integration tests

### PR DESCRIPTION
**Pull request by wochinge**
- we need to tag a new release to fix the Rasa X build https://travis-ci.com/RasaHQ/rasa-x/jobs/268428668

### CODE REVIEW

**Comment by wochinge** [comment]
@dakshvar22 Are you aware that the model size increased in Rasa 1.6 dramatically?

**Comment by dakshvar22** [comment]
@ghostvv @tabergma Seems unlikely, but can the increased model size be because of the new sparse implementation?

**Comment by tabergma** [comment]
@wochinge do you know exactly what increased? I think if you set `return_sequence` to `True` that should take some extra space, but apart from that the model pretty much stayed the same.

**Comment by Ghostvv** [comment]
@wochinge by dramatically, how much exactly? there is 1 additional layer, that can be quite large though

**Comment by wochinge** [comment]
Just check the PR. It's 240 % going from 2mb to 6. I just did `rasa train`

**Comment by Ghostvv** [comment]
that's actually possible with the char config

**Comment by amn41** [comment]
my model size went from 27M to 224M! 10x!

**Comment by tmbo** [comment]
@amn41 when you open the archive, which part is largest?

**Comment by tmbo** [comment]
@Ghostvv @tabergma can you please take a look at this as soon as possible?

**Comment by amn41** [comment]
two checkpoint files, one for embedding classifier, one for response selector:

```
102M Dec 19 09:16 component_7_EmbeddingIntentClassifier.ckpt.data-00000-of-00001
129M Dec 19 09:16 component_8_ResponseSelector.ckpt.data-00000-of-00001
```

**Comment by Ghostvv** [comment]
> but if I remove CountVectorsFeaturizer components (both word and char), using only convert features, it goes down to 12M

in this case, it is the sparse to dense layer weights that occupy so much disc space

**Comment by Ghostvv** [comment]
@tabergma could you please check how many variables did we add with this layer?

**Comment by tabergma** [comment]
According to the helper function I found, the `dense_layer_for_sparse_text/kernel` adds 8348672 variables. For `EmbeddingIntentClassifier` we have a total of 8910696. As the `ResponseSelector` has also sparse features for its labels, it has another even more variables: `dense_layer_for_sparse_label/kernel` adds 1836032 variables.

**Comment by Ghostvv** [comment]
makes sense. How many parameters, does old version have?

**Comment by tabergma** [comment]
Training carbon bot with Rasa 1.5.3 resulted in the following numbers:
`EmbeddingIntentClassifier` has 2385604 variables.
`ResponseSelector` has 3141928 variables.

**Pull request merged**
